version: '3.2'

services:

    nginx:
      build: ./nginx
      restart: always
      depends_on:
        - bot_poster
      ports:
       - "80:80"

    bot_poster:
      restart: always
      build: .
      env_file: .env
      volumes:
        - type: bind
            source: ./logs/
            target: /app/log/